### ISSUE TITLE
Stack smashing detected when running with a shabang

### ISSUE THREAD

**Issue by marmistrz** [marmistrz/randmockery#1]
Use the following script: https://gist.github.com/marmistrz/fd87ae92836f29f7c6a33bd36bec6bca
Run `randmockery ./pi.py`

This triggers stack smashing:
```
*** stack smashing detected ***: python terminated
thread 'main' panicked at 'Unexpected stop reason: Stopped(Pid(14464), SIGSEGV)', src/lib.rs:26
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: randmockery::wait_sigtrap_fun
             at ./src/lib.rs:26
   8: randmockery::intercept_syscalls
             at ./src/lib.rs:131
   9: randmockery::main
             at ./src/main.rs:24
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start
  12: main
  13: __libc_start_main
  14: _start
```

Strace log: https://gist.github.com/marmistrz/0cb4091ca7fc936f0c2767d3409c8ac3

**Comment by marmistrz** [comment]
I spent something like 3 days debugging it, with no luck. It stayed magic. All symptoms, problems described here: https://sourceware.org/ml/libc-help/2017-07/msg00012.html

**Comment by marmistrz** [comment]
Python recompiled with musl doesn't suffer from the same problem but it's probably due to the fact that musl doesn't provide the wrapper for `getrandom(2)` and the raw syscall is used.

**Comment by marmistrz** [comment]
It appears that there are two(!) `SIGTRAPs` issued when using `env`.

**Comment by marmistrz** [comment]
This seems not to happen with 08a7575f96a199c65a3d63e5bc41460a6a710315.
